/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventsscheduler;

//import java.awt.Toolkit;
//import java.awt.event.WindowEvent;
//import java.awt.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashiqul hoque chowdh
 */
public class EventsInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form EventsInfoFrame
     */
    public EventsInfoFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuItemShowEvent = new javax.swing.JMenu();
        MenuItemShowEvents = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuItemManageEvent = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MenuItemShowEvent.setText("Events");
        MenuItemShowEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemShowEventActionPerformed(evt);
            }
        });

        MenuItemShowEvents.setText("Show Events");
        MenuItemShowEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemShowEventsActionPerformed(evt);
            }
        });
        MenuItemShowEvent.add(MenuItemShowEvents);

        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuItemShowEvent.add(MenuItemExit);

        MenuItemManageEvent.setText("ManageEvent");
        MenuItemManageEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemManageEventActionPerformed(evt);
            }
        });
        MenuItemShowEvent.add(MenuItemManageEvent);

        jMenuBar1.add(MenuItemShowEvent);

        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });

        MenuItemAbout.setText("About");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuItemAbout);

        jMenuBar1.add(MenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        // TODO add your handling code here:
                    JOptionPane.showMessageDialog(rootPane, "About: "
                + "\n This application is about to schedule one's events.");  
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    private void MenuItemShowEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemShowEventActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuItemShowEventActionPerformed

    private void MenuItemManageEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemManageEventActionPerformed
        // TODO add your handling code here:
      //  close();
        if(ManageEventFrame.y==0){ 
        ManageEventFrame frame =   new ManageEventFrame();
        frame.setVisible(true);
        frame.setLocation(500, 150);
        }
        else{
        JOptionPane.showMessageDialog(null, "This window is already visible "); 
        }
        
    }//GEN-LAST:event_MenuItemManageEventActionPerformed

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        // TODO add your handling code here:
        //ExitConfirmation
        int confirmation=JOptionPane.showConfirmDialog(null,"Do you really want to exit","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmation==0){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuItemShowEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemShowEventsActionPerformed
        // TODO add your handling code here:
     //   close();
        if(ShowEventsFrame.x==0){
        ShowEventsFrame frame = new ShowEventsFrame();
        frame.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null, "This window is already visible "); 
        }
        
    }//GEN-LAST:event_MenuItemShowEventsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuItemAbout;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemManageEvent;
    private javax.swing.JMenu MenuItemShowEvent;
    private javax.swing.JMenuItem MenuItemShowEvents;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void close() {
        setDefaultCloseOperation(EventsInfoFrame.DISPOSE_ON_CLOSE); 
        WindowEvent winClosingEvent =new WindowEvent(this,WindowEvent.WINDOW_CLOSING); 
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
}
